### ISSUE TITLE
SLF4J test Logger function is not working

### ISSUE THREAD

**Issue by rajakirsh** [Mahoney/slf4j-test#6]
Hi,

I tried the code based on the sample given. But it was always throwing there is no events in the logger.

I have pasted below the code, log, error for your review. Could you please clarify and help?

Thanks

Raja

package com.charter.aesd.tvgo.app.quartz;

import java.text.ParseException;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;

import javax.annotation.concurrent.Immutable;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.quartz.CronScheduleBuilder;
import org.quartz.JobBuilder;
import org.quartz.JobDetail;
import org.quartz.JobKey;
import org.quartz.Scheduler;
import org.quartz.SchedulerException;
import org.quartz.Trigger;
import org.quartz.TriggerBuilder;
import org.quartz.impl.StdSchedulerFactory;
import org.quartz.impl.matchers.GroupMatcher;

import uk.org.lidalia.slf4jtest.LoggingEvent;
import uk.org.lidalia.slf4jtest.TestLogger;
import uk.org.lidalia.slf4jtest.TestLoggerFactory;

import ch.qos.logback.core.AppenderBase;

import com.charter.aesd.tvgo.transform.conf.LocalS3ClientModule;
import com.charter.aesd.tvgo.transform.conf.LocalTransformationModule;
import com.google.common.collect.ImmutableList;
import com.google.inject.Guice;
import com.google.inject.Injector;
import static uk.org.lidalia.slf4jtest.LoggingEvent.info;
import static java.util.Arrays.asList;
import static org.junit.Assert.assertThat;
import static org.hamcrest.Matchers.is;

public class TvGoSchedulerTest {

```
   /* SLF4J logger with logback */ 
TestLogger logger = TestLoggerFactory.getTestLogger(TvGoFeedSchedulerListener.class);


   @Test
   public void  schedulerTest() throws ParseException, SchedulerException, InterruptedException {
        //schedule it
        Injector injector = Guice.createInjector(new LocalTransformationModule(), new LocalS3ClientModule());
        TvGoFeedJob job = injector.getInstance(TvGoFeedJob.class);

        JobKey jobKeyDummy = new JobKey("jobDummy", "group1");
        JobDetail jobDummy = JobBuilder.newJob(job.getClass())
        .withIdentity(jobKeyDummy).build();


        Trigger triggerDummy = TriggerBuilder
                .newTrigger()
                .withIdentity("triggerDummy", "trgGroup1")
                .withSchedule(
                    CronScheduleBuilder.cronSchedule("0 0/1 * 1/1 * ? *"))
                .build();


        Scheduler scheduler = new StdSchedulerFactory().getScheduler();
        scheduler.getListenerManager().addSchedulerListener(new TvGoFeedSchedulerListener());

        //assertThat(logger.getLoggingEvents(), is(asList(info("Job jobDummy from group group1 is Added to scheduler"))));
        scheduler.start();
        assertThat(logger.getLoggingEvents(), is(asList(info("Scheduler is Started"))));
        scheduler.pauseJob(jobKeyDummy);
        scheduler.resumeJob(jobKeyDummy);
        scheduler.addJob(jobDummy,true);
        scheduler.pauseTrigger(triggerDummy.getKey());
        scheduler.resumeTrigger(triggerDummy.getKey());
        GroupMatcher<JobKey> group = GroupMatcher.groupContains("group");
        scheduler.pauseJobs(group);
        scheduler.resumeJobs(group);
        scheduler.clear();
        scheduler.deleteJob(jobDummy.getKey());
        scheduler.standby();
        scheduler.scheduleJob(jobDummy, triggerDummy);


        scheduler.shutdown();
    }

   @After
   public void clearLog(){
       TestLoggerFactory.clear();

   }
```

}

---

Actual Log

21:18:23.564 [main] INFO  c.c.a.t.a.q.TvGoFeedSchedulerListener - Scheduler is Started
21:18:23.564 [main] INFO  c.c.a.t.a.q.TvGoFeedSchedulerListener - Job jobDummy from group group1 is Paused
21:18:23.568 [main] INFO  c.c.a.t.a.q.TvGoFeedSchedulerListener - Job jobDummy from group group1 is Resumed
21:18:23.568 [main] INFO  c.c.a.t.a.q.TvGoFeedSchedulerListener - Job jobDummy from group group1 is Added to scheduler
21:18:23.568 [main] INFO  c.c.a.t.a.q.TvGoFeedSchedulerListener - Trigger triggerDummy of group trgGroup1 is Paused
21:18:23.568 [main] INFO  c.c.a.t.a.q.TvGoFeedSchedulerListener - Trigger triggerDummy of group trgGroup1 is Resumed
21:18:23.578 [main] INFO  c.c.a.t.a.q.TvGoFeedSchedulerListener - Jobs in Group group1 Paused
21:18:23.578 [main] INFO  c.c.a.t.a.q.TvGoFeedSchedulerListener - Jobs in Group group1 Resumed
21:18:23.578 [main] INFO  c.c.a.t.a.q.TvGoFeedSchedulerListener - Scheduling Data Cleared
21:18:23.578 [main] INFO  o.q.c.QuartzScheduler - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED paused.
21:18:23.579 [main] INFO  c.c.a.t.a.q.TvGoFeedSchedulerListener - Job Scheduler in StandByMode
21:18:23.585 [main] INFO  c.c.a.t.a.q.TvGoFeedSchedulerListener - Job jobDummy from group group1 is Added to scheduler
21:18:23.585 [main] INFO  c.c.a.t.a.q.TvGoFeedSchedulerListener - Job jobDummy of group group1 is Scheduled to start at Thu May 01 21:18:23 IST 2014
21:18:23.588 [main] INFO  o.q.c.QuartzScheduler - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED shutting down.
21:18:23.588 [main] INFO  o.q.c.QuartzScheduler - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED paused.
21:18:23.588 [main] INFO  c.c.a.t.a.q.TvGoFeedSchedulerListener - Job Scheduler in StandByMode
21:18:23.588 [main] INFO  c.c.a.t.a.q.TvGoFeedSchedulerListener - Scheduler is Shutting Down
21:18:23.588 [main] INFO  c.c.a.t.a.q.TvGoFeedSchedulerListener - Scheduler ShutDown
21:18:23.588 [main] INFO  o.q.c.QuartzScheduler - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED shutdown complete.

---

Error Trace

java.lang.AssertionError: 
Expected: is <[LoggingEvent[level=INFO,mdc={},marker=Optional.absent(),throwable=Optional.absent(),message=Scheduler is Started,arguments=[]]]>
     but: was <[]>
    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
    at org.junit.Assert.assertThat(Assert.java:865)
    at org.junit.Assert.assertThat(Assert.java:832)
    at com.charter.aesd.tvgo.app.quartz.TvGoSchedulerTest.schedulerTest(TvGoSchedulerTest.java:72)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

**Comment by Selindek** [comment]
It works perfectly when I run the test with maven, but when I'm working in Eclipse and run the Junit-tests using Eclipse's test-runner, then it doesn't exclude the original logback-classic logger.
Is there any way to make it work under Eclipse?
